name: reusable-linux
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"

jobs:
  machine-prepare:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Tailscale setup 
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh && \
          sudo tailscale up --auth-key=${{secrets.TAILSCALEKEY}}

      - name: getIP
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to debug from the host \`tailscale ssh runner@${IP}\` or \`rshell runner@${IP}\`"
          sleep 18000

      - name: Message user; 1 hour
        run: |
          sudo wall "about 1 hour remaining"
          sleep 1800