name: ubuntu-runner-with-repository
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"
      repository:
        description: "Target repository"
        required: true
        type: choice
        options:
          - "ci-definitions"
          - "crc"
          - "macadam"
          - "deliverest"
          - "mapt"
          - "concurrency-control"
          - "crc-performance"
# avaliable runner can be check https://github.com/actions/runner-images
jobs:
  machine-prepare:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Tailscale setup 
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh && \
          sudo tailscale up --auth-key=${{secrets.TAILSCALEKEY}}

      - name: setup ssh 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys

      - name: install go 
        run: |
          wget https://go.dev/dl/go1.23.1.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          go version

      - name: clone repository
        run: |
          address="https://github.com/lilyLuLiu/${{ inputs.repository }}.git" && \
          git clone $address && \
          cd $(basename -s .git $address) && \
          ls -al

      - name: getIP
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to debug from the host \`tailscale ssh runner@${IP}\` or \`rshell runner@${IP}\`"
          sleep 18000

      - name: Message user; 1 hour
        run: |
          sudo wall "about 30 min remaining"
          sleep 1800